version: '3'

services:

  web:
    build: ./backend
    command: gunicorn -w 4 -b 0.0.0.0:5000 backend.wsgi:app
    env_file: .env
    depends_on:
      - db

  db:
    image: mongo

  nginx:
    build: ./nginx
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - web
